accounts/urls.py
# import patterns as patterns
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.login, name='login'),
    path(r'forgot/', views.forgot, name='forgot'),
    path(r'logout/', views.pagelogout, name='logout'),
    path(r'newpassword', views.updateUrlProfile, name='newPassword'),
]

oxiterp/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf.urls import include

from django.conf import settings
from django.contrib.staticfiles.urls import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('vira/', include('vira.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'education.Views.ErrorViews.page_not_found'
# handler500 = 'education.Views.ErrorViews.page_not_found'

vira/urls.py
from django.urls import path
from vira.Views import MainView, DoctorViews, PersonView

app_name = 'vira'
urlpatterns = [
    # Dashboard
    path('main/', MainView.view_main, name='view_main'),
    #Doctor
    path('doctor/', DoctorViews.view_doctor, name='view_doctor'),
    path('doctor/delete', DoctorViews.delete_patient, name='delete_patient'),

    # User
    path('person/', PersonView.change_user, name='change_user'),

]

accounts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class Forgot(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import Permission


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'id': 'username'}))
    password = forms.CharField(label="Password", max_length=30, widget=forms.TextInput(
        attrs={'class': 'mdl-textfield__input', 'type': 'password', 'id': 'password'}))

accounts/views.py
from urllib.parse import urlparse

from django.contrib import auth, messages
from django.contrib.auth import logout
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import  User
from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.shortcuts import render, redirect

from accounts.models import Forgot

def login(request):
    if request.user.is_authenticated is True:
        return redirect('vira:view_main')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('vira:view_main')
        else:
            return redirect('accounts:logout')
    return render(request, 'login.html')


def pagelogout(request):
    logout(request)
    return redirect('accounts:login')

def updateUrlProfile(request):
    if request.method == 'GET':

        try:

            data = request.GET.get('query')
            forgot = Forgot.objects.get(uuid=data)
            user = forgot.user
            password_form = SetPasswordForm(user)
            if forgot.status == False:
                forgot.status = True
                forgot.save()
                return render(request, 'newPassword.html',
                              {'password_form': password_form})
            return redirect('accounts:login')

        except:
            return redirect('accounts:login')

    if request.method == 'POST':
        with transaction.atomic():
            try:
                forgot = Forgot.objects.get(uuid=request.GET.get('query'))
                password_form = SetPasswordForm(forgot.user, request.POST)
                user = forgot.user
                if password_form.is_valid():
                    user.set_password(password_form.cleaned_data['new_password1'])
                    user.save()
                    # zaman kontrolüde yapilacak
                    forgot.status = True
                    messages.success(request, 'Şifre Başarıyla Güncellenmiştir.')

                    return redirect('accounts:login')


                else:

                    messages.warning(request, 'Alanları Kontrol Ediniz')
                    return render(request, 'newPassword.html',
                                  {'password_form': password_form})
            except:
                return redirect('accounts:login')

    return render(request, 'accounts/index.html')


def forgot(request):
    if request.method == 'POST':
        mail = request.POST.get('username')
        if User.objects.filter(username=mail):
            user=User.objects.get(username=mail)
            fdk = Forgot(user=user, status=False)
            fdk.save()
            url = urlparse(request.META.get('HTTP_REFERER')).hostname

            html_content = ''
            subject, from_email, to = 'Bilgi Sistemi Kullanıcı Bilgileri', 'fatih@kobiltek.com', mail
            html_content = '<h2>ADALET BAKANLIGI PROJE TAKİP  SİSTEMİ</h2>'
            html_content = html_content + '<p><strong>Kullanıcı Adınız :' + str(fdk.user.username) + '</strong></p>'
            if url == 'kobiltek.com':
                html_content = html_content + '<p> <strong>Yeni şifre oluşturma linki:</strong> <a href="http://www.kobiltek.com:81/yks/sbs/newpassword?query=' + str(
                    fdk.uuid) + '">http://www.kobiltek.com:81/yks/sbs/profil-guncelle/?query=' + str(
                    fdk.uuid) + '</p></a>'
            else:
                html_content = html_content + '<p> <strong>Site adresi:</strong> <a href="http://127.0.0.1:8000/newpassword?query=' + str(
                    fdk.uuid) + '">http://127.0.0.1:8000/sbs/profil-guncelle/?query=' + str(fdk.uuid) + '</p></a>'



            msg = EmailMultiAlternatives(subject, '', from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            messages.success(request, "Giriş bilgileriniz mail adresinize gönderildi. ")
            return redirect("accounts:login")
        else:
            messages.warning(request, "Geçerli bir mail adresi giriniz.")
            return redirect("accounts:forgot")

    return render(request, 'forgot-password.html')

accounts/templates/forgot-password.html
<!DOCTYPE html>
<html style="overflow-y: hidden">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>YÖNETİM KONTROL SİSTEMİ</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    {% load static %}
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %} ">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">

<div class="login-box">
    <div class="login-logo">
        <span class="logo-lg"><img width="80%" src="{% static 'images/giris-logo.png' %}" alt="User Image" style="margin-bottom: 5px;"> </span>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Şifre Hatırlama için
            Mail Adresinizi Giriniz </p>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message.message }}</li>

                {% endfor %}
            </ul>
        {% endif %}




        <form action="" method="post">


            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="mail" class="form-control" placeholder="Mail Adresiniz" name="username">

                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>


            <div class="row">
                <div class="col-xs-8">

                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Gönder</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
        <a href="{% url 'accounts:login' %}" class="text-center">Giriş Yap</a><br>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

accounts/templates/login.html
{% extends "base_layout.html" %}

{% block main %}

    <div id="content" class="site-content">
        <div class="container">
            <div class="sml-page-wrap no-sidebar">
                <div id="primary" class="content-area">
                    <main id="main" class="site-main">

                        <article id="post-121" class="post-121 page type-page status-publish hentry">
                            <div class="sml-single-page-wrapp">

                                <div class="entry-content">
                                    <div class="woocommerce">
                                        <div class="woocommerce-notices-wrapper"></div>

                                        <div class="u-columns col2-set" id="customer_login">

                                            <div class="u-column1 col-1">


                                                <h2>Login (admin vira2021)</h2>

                                                <form class="woocommerce-form woocommerce-form-login login"
                                                      method="post">
                                                    {% csrf_token %}

                                                    <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                        <label for="username">Username or email address&nbsp;<span
                                                                class="required" required="required">*</span></label>
                                                        <input type="text"
                                                               class="woocommerce-Input woocommerce-Input--text input-text"
                                                               name="username" id="username" autocomplete="username"
                                                               value=""></p>
                                                    <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                        <label for="password">Password&nbsp;<span class="required"
                                                                                                  required="required">*</span></label>
                                                        <span class="password-input"><input
                                                                class="woocommerce-Input woocommerce-Input--text input-text"
                                                                type="password" name="password" id="password"
                                                                autocomplete="current-password"><span
                                                                class="show-password-input"></span></span>
                                                    </p>


                                                    <p class="form-row">
                                                        <label class="woocommerce-form__label woocommerce-form__label-for-checkbox woocommerce-form-login__rememberme">
                                                            <input class="woocommerce-form__input woocommerce-form__input-checkbox"
                                                                   name="rememberme" type="checkbox" id="rememberme"
                                                                   value="forever"> <span>Remember me</span>
                                                        </label>
                                                        <input type="hidden" id="woocommerce-login-nonce"
                                                               name="woocommerce-login-nonce" value="41747f64fe"><input
                                                            type="hidden" name="_wp_http_referer"
                                                            value="/my-account/?_ga=2.48395247.871975586.1634652093-587927487.1634652093">
                                                        <button type="submit"
                                                                class="woocommerce-button button woocommerce-form-login__submit"
                                                                name="login" value="Log in">Log in
                                                        </button>
                                                    </p>
                                                    <p class="woocommerce-LostPassword lost_password">
                                                        <a href="https://shop.virasoft.com/my-account/lost-password/">Lost
                                                            your password?</a>
                                                    </p>


                                                </form>


                                            </div>



                                        </div>

                                    </div>
                                </div><!-- .entry-content -->
                            </div>

                        </article><!-- #post-121 -->

                    </main><!-- #main -->
                </div><!-- #primary -->
            </div>
        </div>

    </div>

{% endblock %}

accounts/templates/newPassword.html
<!DOCTYPE html>
<html style="overflow-y: hidden">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>YÖNETİM KONTROL SİSTEMİ</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    {% load static %}
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %} ">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">

<div class="login-box">
    <div class="login-logo">
        <span class="logo-lg"><img width="80%" src="{% static 'images/giris-logo.png' %}" alt="User Image" style="margin-bottom: 5px;"> </span>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Hoşgeldiniz</p>


        {% if messages %}







            <ul class="messages">

            {% for message in messages %}

                <li class="{{ message.tags }}">{{ message }}</li>

            {% endfor %}


        {% endif %}

        <div class="row">

            <form method="post" enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="row">

                    <div class="col-lg-12">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">Şifre İşlemleri</h3>
                            </div>
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-lg-12">

                                        <div class="form-group">

                                            {{ password_form }}
                                        </div>
                                    </div>

                                </div>

                            </div>
                            <div class="box-footer">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                            </div>


                        </div>


                    </div>


                </div>

            </form>

        </div>


    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

vira/templates/Doctor/view_doctor.html
{% extends 'base_layout.html' %}
{% block main %}
    <div id="content" class="site-content">
        <div class="container">
            <div class="sml-page-wrap no-sidebar">
                <div id="primary" class="content-area">


                    <main id="main" class="site-main">

                        <article id="post-121" class="post-121 page type-page status-publish hentry">
                            <div class="sml-single-page-wrapp">

                                <div class="entry-content">
                                    <div class="woocommerce">


                                        <h2>Hasta Bilgilerini Giriniz:</h2>

                                        <form class="woocommerce-form woocommerce-form-login login"
                                              method="post"
                                              id="patientform">
                                            {% csrf_token %}

                                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                <label>{{ patiend_form.name.label }}</label>
                                                {{ patiend_form.name }}</p>


                                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                <label>{{ patiend_form.surname.label }}</label>
                                                {{ patiend_form.surname }}</p>

                                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                <label>{{ patiend_form.tc.label }}</label>
                                                {{ patiend_form.tc }}</p>

                                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                                <label>{{ patiend_form.cancerType.label }}</label>
                                                {{ patiend_form.cancerType }}</p>


                                            <p class="form-row">

                                                <button type="submit"
                                                        style="margin-top: 20px; text-align: left"
                                                        class="woocommerce-button button woocommerce-form-login__submit"
                                                        value="Log in">Kaydet
                                                </button>
                                            </p>

                                            <input type="hidden" id="custId" name="custId" value="">


                                        </form>


                                    </div>

                                </div>
                            </div><!-- .entry-content -->


                            <table id="patientable" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>İSİM</th>
                                    <th>SOYİSİM</th>
                                    <th>TC NUMARASI</th>
                                    <th>KANSER TÜRÜ</th>
                                    <th>İŞLEMLER</th>

                                </tr>
                                </thead>

                                <tbody>

                                {% if patinets %}
                                    {% for patient in patinets %}
                                        <tr id="patient-{{ patient.pk }}">
                                            <td>{{ forloop.counter }} </td>
                                            <td>{{ patient.name }}</td>
                                            <td>{{ patient.surname }}</td>
                                            <td>{{ patient.tc }}</td>
                                            <td>{{ patient.cancerType }}</td>
                                            <td>
                                                <button data="{{ patient.pk }}"
                                                        class="btnchange"
                                                        type="button">Güncelle
                                                </button>
                                                <button
                                                        class="btndelete"
                                                        type="button" data="{{ patient.pk }}">Sil

                                                </button>


                                        </tr>

                                    {% endfor %}
                                {% endif %}


                                </tbody>
                            </table>


                        </article><!-- #post-121 -->

                    </main><!-- #main -->
                </div><!-- #primary -->
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {

            $(".btnchange").click(function (e) {

                var pk = $(this).attr("data")
                $("#custId").val(pk);

                $("#patient-" + pk).find("td").eq(1).html();
                $("#id_name").val($("#patient-" + pk).find("td").eq(1).html());
                $("#id_surname").val($("#patient-" + pk).find("td").eq(2).html());
                $("#id_tc").val($("#patient-" + pk).find("td").eq(3).html());

            });


            $(".btndelete").click(function (e) {
                var pk = $(this).attr("data")
                if (e.handled !== true) { // This will prevent event triggering more then once
                    e.handled = true;
                    if (pk != null) {
                        $.ajax({
                            type: "POST",
                            url: "{% url "vira:delete_patient" %}",
                            data: {
                                'csrfmiddlewaretoken': "{{  csrf_token  }}",
                                'isActive': 'False',
                                'pk': pk.toString(),
                            },
                            success: function (data) {
                                if (data.status == "Success") {
                                    $('#patient-' + pk.toString()).remove();
                                    console.log(pk + "idli deger başarı ile silindi")
                                }

                            }
                        });
                    }
                }
            });


            $("#patientform").submit(function (e) {

                e.preventDefault();
                var form = $(this);
                var url = form.attr('action');
                if (e.handled !== true) { // This will prevent event triggering more then once
                    e.handled = true;

                    $.ajax({
                        type: "POST",
                        url: url,
                        data: form.serialize(),
                        success: function (data) {
                            if (data.status == "Success") {
                                $('#patientable').append("<tr> <td>" + data.count + "</td><td>" + $("#id_name").val() + "</td> <td>" + $("#id_surname").val() + "</td> <td>" + $("#id_tc").val() + "</td><td>" + $("#id_cancerType option:selected").text() + "</td><td>işlemler</td></tr>");
                                $("input").val(null);
                            }
                        }
                    });
                }
            });
        });

    </script>
{% endblock %}

vira/templates/Main/main.html
{% extends 'base_layout.html' %}
{% block main %}





    {% load static %}

    <link
            type="text/css"
            href="https://uicdn.toast.com/tui-color-picker/v2.2.6/tui-color-picker.css"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static "image-editor/dist/tui-image-editor.css" %}">
    <style>
        @import url(http://fonts.googleapis.com/css?family=Noto+Sans);

        html,
        .imageeditor {
            height: 800px;
            margin: 0;
        }
    </style>

    <img src="" id="imageWatch" alt="berktug">


    <div class="imageeditor">
        <div id="tui-image-editor-container"></div>

    </div>
    <script
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.4.0/fabric.js"
    ></script>
    <script
            type="text/javascript"
            src="https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://uicdn.toast.com/tui-color-picker/v2.2.6/tui-color-picker.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"
    ></script>


    <script src="{% static 'image-editor/dist/tui-image-editor.js' %}"></script>
    <script src="{% static 'image-editor/js/theme/white-theme.js' %}"></script>
    <script src="{% static 'image-editor/js/theme/black-theme.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script>


        $(document).ready(function () {
            $("#file-upload-button").change(function (e) {
               alert()
            });


            // Image editor
            var imageEditor = new tui.ImageEditor('#tui-image-editor-container', {
                includeUI: {
                    loadImage: {
                        path: '/static/image-editor/img/desired_mask.png',
                        name: 'Desired_mask',
                    },
                    initMenu: 'filter',
                    menuBarPosition: 'bottom',
                },
                cssMaxWidth: 700,
                cssMaxHeight: 500,
                usageStatistics: false,
            });
            window.onresize = function () {
                imageEditor.ui.resizeEditor();
            }

        })
    </script>

{% endblock %}